name: Update Docker Hub Description
on:
  push:
    branches:
      - master
    paths:
      - readme.md
      - .github/workflows/dockerhub-readme.yml
jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}
        readme-filepath: ./readme.md
